### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by allyson-dudley** [fun-test-org/fun-test-repo#1]
The "fun" repo is actually quite boring.

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 100

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 200

Let's try now with more text and also changing the total

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 200

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash 200

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash 50

**Comment by rodrigolece** [comment]
@quine-bot-dev embark

I'm also trying here to add more text

**Comment by rodrigolece** [comment]
@quine-bot-dev embark

**Comment by rodrigolece** [comment]
@quest-bot-dev embark

retrying with the correct bot (and more text)

**Comment by rodrigolece** [comment]
@quest-bot-dev embark

**Comment by rodrigolece** [comment]
@quest-bot-dev embark

**Comment by allyson-dudley** [comment]
@quest-bot-dev embark

**Comment by allyson-dudley** [comment]
@quest-bot-dev reward rodrigolece

**Comment by allyson-dudley** [comment]
@quest-bot-dev reward rodrigolece

**Comment by allyson-dudley** [comment]
@quest-bot-dev abort

**Comment by allyson-dudley** [comment]
Closing in order to test functionality on closed issues.

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 200

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash 200
