### ISSUE TITLE
Improve README v2

### ISSUE THREAD

**Issue by allyson-dudley** [fun-test-org/fun-test-repo#3]
Trying again after the bot failed to reward @rodrigolece

**Comment by allyson-dudley** [comment]
@quine-bot-dev stash 100

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 100

**Comment by allyson-dudley** [comment]
@quest-bot-dev reward rodrigolece

**Comment by rodrigolece** [comment]
@quest-bot-dev loot 3

**Comment by rodrigolece** [comment]
@quest-bot-dev abort

**Comment by allyson-dudley** [comment]
@quest-bot-dev abort
