### ISSUE TITLE
Massive prize if you update README

### ISSUE THREAD

**Issue by allyson-dudley** [fun-test-org/fun-test-repo#5]
@quest-bot-dev stash 5000

**Comment by allyson-dudley** [comment]
@quest-bot-dev stash 1000

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash 5000

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash -100

**Comment by allyson-dudley** [comment]
@quest-bot-dev edit -100

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash 100.5

**Comment by allyson-dudley** [comment]
@quest-bot-dev restash pizza

**Comment by rodrigolece** [comment]
Just realised that I forgot to `embark` so will do that now. Note that I've already `looted` with PR #7

**Comment by rodrigolece** [comment]
@quest-dev-bot embark

**Comment by rodrigolece** [comment]
@quest-bot-dev embard

**Comment by rodrigolece** [comment]
@quest-bot-dev embark

**Comment by allyson-dudley** [comment]
@quest-bot-dev abort
